apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-analytics-service
  labels:
    {{- include "url-shortener.labels" . | nindent 4}}
spec:
  selector:
    {{- include "url-shortener.analyticsLabels" . | nindent 4}}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.targetPort }}
