apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-gateway-service
  labels:
    {{- include "url-shortener.labels" . | nindent 4}}
spec:
  selector:
    app: {{ include "url-shortener.fullname" . }}-gateway-service
  ports:
  - name: http
    port: {{ .Values.gatewayService.port }}
    targetPort: {{ .Values.gatewayService.port }}
    nodePort: {{ .Values.gatewayService.service.nodePort }}
  type: NodePort
