apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volume.claimName | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.volume.storage }}