apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.fullname" .}}-redis
  labels:
    {{- include "url-shortener.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "url-shortener.redisLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "url-shortener.redisLabels" . | nindent 8}}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.redis.port }}
          initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}