apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" .}}-redis
  labels:
    {{- include "url-shortener.labels" . | nindent 4}}
spec:
  ports:
  - port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ include "url-shortener.fullname" .}}-redis
