apiVersion: v1
kind: Service
metadata:
  name: {{include "url-shortener.fullname" .}}-url-service
  labels:
    {{- include "url-shortener.labels" . | nindent 4}}
spec:
  selector:
    app: {{include "url-shortener.fullname" . }}-url-service
  ports:
  - name: url-service
    port: {{ .Values.urlService.port}}
    targetPort: {{ .Values.urlService.port}}
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.targetPort }}
