apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
