apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-service
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
      - name: url-service
        image: url-service:latest
        ports:
        - containerPort: 50051
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: urlshortener
        - name: DB_SSLMODE
          value: disable
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
