analyticsService:
  replicaCount: 1
  image:
    repository: ghcr.io/sammyqtran/analytics-service
    tag: latest
    pullPolicy: IfNotPresent

gatewayService:
  replicaCount: 1
  image:
    repository: ghcr.io/sammyqtran/gateway-service
    tag: latest
    imagePullPolicy: IfNotPresent
  port: 8080
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    nodePort: 31081


urlService:
  replicaCount: 1
  image:
    repository: ghcr.io/sammyqtran/url-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 50051
  host: prod-url-shortener-url-service
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  env:
    DB_HOST: prod-url-shortener-postgres
    DB_PORT: "5432"
    DB_USER: postgres
    DB_PASSWORD: password
    DB_NAME: urlshortener
    DB_SSLMODE: disable
    REDIS_ADDR: prod-url-shortener-redis:6379 
    REDIS_PASSWORD: "" 

metrics:
  port: 2112
  targetPort: 2112
  nodePort: 30495

redis:
  address: prod-url-shortener-redis:6379
  password: ""
  port: 6379
  image:
    repository: redis
    tag: "7"
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10

postgres:
  image:
    repository: postgres
    tag: 15-alpine
  database: urlshortener
  user: postgres
  password: password
  containerPort: 5432
  volume:
    mountPath: /var/lib/postgresql/data
    claimName: postgres-pvc
    storage: 1Gi
  readinessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
        - -d
        - urlshortener
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
