version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - url-service
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urlshortener"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  url-service:
    build:
      context: .
      dockerfile: ./cmd/url-service/Dockerfile
    container_name: url-shortener-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: urlshortener
      DB_SSLMODE: disable
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge