{
 "title": "metrics2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "DB Operation Duration (95th Pctl)\t",
   "type": "timeseries",
   "description": "95th percentile DB operation latency\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_operation_duration_seconds_bucket[1m])) by (le, service, operation))\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "errors/sec\t" } },
   "targets": [
    {
     "expr": "sum(rate(db_errors_total[1m])) by (service, operation)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Operations Total\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(db_operations_total[1m])) by (service, operation)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Errors\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "errors/sec\t" } },
   "targets": [
    {
     "expr": "sum(rate(cache_errors_total[1m])) by (service, cache, operation)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses\t",
   "type": "timeseries",
   "description": "sum(rate(cache_misses_total[1m])) by (service, cache)\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "misses/sec\t" } },
   "targets": [
    {
     "expr": "sum(rate(cache_misses_total[1m])) by (service, cache)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hits/sec\t" } },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total[1m])) by (service, cache)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Event Latency\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(consume_event_duration_seconds_bucket[1m])) by (le, service, event))\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Event Errors\t",
   "type": "timeseries",
   "description": "Consuming errors rate\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(consume_event_errors_total[1m])) by (service, event)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Events Total\t",
   "type": "timeseries",
   "description": "Total events consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(consume_events_total[1m])) by (service, event)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Event Latency\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(publish_event_duration_seconds_bucket[1m])) by (le, service, event))\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Event Errors\t",
   "type": "timeseries",
   "description": "Publishing errors rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "errors/sec\t" } },
   "targets": [
    {
     "expr": "sum(rate(publish_event_errors_total[1m])) by (service, event)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Events Total",
   "type": "timeseries",
   "description": "Total events published per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(publish_events_total[1m])) by (service, event)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Call Latency (95th Pctl)",
   "type": "timeseries",
   "description": "95th percentile gRPC call latenc",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_call_duration_seconds_bucket[1m])) by (le, service, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_errors_total[1m])) by (service, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Calls Total",
   "type": "timeseries",
   "description": "Total gRPC calls per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "calls/sec" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_calls_total[1m])) by (service, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "description": "95th percentile HTTP request latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, service, method, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Errors by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m])) by (status_code)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}