name: Go CI with Docker Compose and Test Client

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Download dependencies
        run: go mod download

      - name: Build and start services via docker-compose
        run: |
          docker compose up -d --build
          
          # Wait for postgres health
          for i in {1..30}; do
            status=$(docker inspect --format='{{json .State.Health.Status}}' url-shortener-postgres || echo "null")
            if [[ "$status" == "\"healthy\"" ]]; then
              echo "Postgres is healthy"
              break
            fi
            echo "Waiting for Postgres to be healthy..."
            sleep 2
          done

      - name: Run url-service tests
        working-directory: ./cmd/url-service
        run: go test -v ./...

      - name: Run gateway-service tests
        working-directory: ./cmd/gateway-service
        run: go test -v ./...

      - name: Run test client to verify grpc service
        working-directory: ./cmd/test-client/url-service-test-client
        run: go run main.go

      - name: Run test client to verify handlers service
        working-directory: ./cmd/test-client/gateway-service-test-client
        run: go run main.go        

      - name: Tear down docker-compose
        run: docker compose down
