name: Deploy to Local Kubernetes

on:
  workflow_run:
    workflows: ["Go CI with Build, Test, and Docker Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Pull latest images
        run: |
          docker pull ghcr.io/sammyqtran/url-service:latest
          docker pull ghcr.io/sammyqtran/gateway-service:latest
          docker pull ghcr.io/sammyqtran/analytics-service:latest

      - name: Rollout deployments
        run: |
          kubectl rollout restart deployment/dev-url-shortener-url-service -n default
          kubectl rollout restart deployment/dev-url-shortener-gateway-service -n default
          kubectl rollout restart deployment/dev-url-shortener-analytics-service -n default

      - name: Wait for deployments to be ready
        run: |
          kubectl rollout status deployment/dev-url-shortener-url-service -n default --timeout=120s
          kubectl rollout status deployment/dev-url-shortener-gateway-service -n default --timeout=120s
          kubectl rollout status deployment/dev-url-shortener-analytics-service -n default --timeout=120s
      
      - name: Run Integration test
        run: |
          kubectl port-forward svc/dev-url-shortener-gateway-service 8080:8080 &
          GATEWAY_PID=$!
          sleep 3

          kubectl port-forward svc/dev-url-shortener-url-service 50051:50051 &
          URL_PID=$!

          sleep 5 
          cd /home/sammy/dev/hello-go/
          ./testingscripts/run-test-clients.sh
          
          for PID in $GATEWAY_PID $URL_PID; do
            if ps -p $PID -o cmd= | grep -q 'kubectl port-forward'; then
              kill $PID
            fi
          done